SKILLS = [
    "python",
    "java",
    "c",
    "c++",
    "sql",
    "html",
    "css",
    "javascript",
    "flask",
    "django",
    "machine learning",
    "deep learning",
    "data structures",
    "algorithms",
    "git",
    "github",
    "mongodb",
    "mysql",
    "linux",
    "aws",
    "docker",
    "communication",
    "problem solving"
]